CREATE TABLE IF NOT EXISTS users
(
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (name),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS massages
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(4096)                           NOT NULL,
    author  VARCHAR(255)                            NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_massages PRIMARY KEY (id),
    FOREIGN KEY (author) REFERENCES users (name) ON DELETE CASCADE
);